title: ManuelAMS
description: Mis proyectillos
author: ManuelAMS
logo: /static/img/avatar.jpg
github: https://github.com/ManuelAMS
about: Freelance police

#baseurl: "http://aboutashu.com/hcz-jekyll-blog"
#url: "http://aboutashu.com/hcz-jekyll-blog"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [github-pages, jekyll-paginate, jekyll-gist]
