title: ManuelAMS (Pelayo)
description: Mis proyectillos
author: ManuelAMS (Pelayo)
logo: /static/img/avatar.jpg
github: https://github.com/ManuelAMS
about: Freelance police

#baseurl: "https://manuelams.github.io"
#url: "https://manuelams.github.io"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [github-pages, jekyll-paginate, jekyll-gist]
